[webservers]
web-1 ansible_host=62.84.120.144 ansible_user=alex_2025 ansible_ssh_private_key_file=~/.ssh/id_ed25519
web-2 ansible_host=89.169.164.95 ansible_user=alex_2025 ansible_ssh_private_key_file=~/.ssh/id_ed25519
